### ISSUE TITLE
NoMethodError in Users#profile

### ISSUE THREAD

**Issue by git-e-up** [git-e-up/Stripe_Fees#1]
Andrew,
I committed the code you helped with yesterday and keep getting errors. I've tried everything I can think of... renamed the "key" method in the users controller to "api_key", tried moving the method to the User model, removed the conditional on the views/users/profile, tried moving the formula to a new erb page called "api_key", etc. etc. 
For some reason it doesn't understand what "api_key" is in any circumstance. Sorry to bother you on the weekend... If you have a chance to look it over, that would be great. Otherwise I'll see you Tuesday. 
Thanks,
Matt
![screen shot 2015-05-24 at 10 33 07 am](https://cloud.githubusercontent.com/assets/11341488/7788438/649c6dda-0200-11e5-923f-dd2dff4035bb.png)

**Comment by git-e-up** [comment]
James,
If you have any idea what to do here... that would be appreciated. I know you didn't write this portion of the code, but I think Andrew's intention was that a user would enter their Stripe API info on on their profile page.

**Comment by amadden80** [comment]
Hi Matt,

It seems your user model does not have an attribute called `api_key`.
Does the user model have an `api_key` in the database migration?

Maybe you need to add `t.string :api_key` to the users table database migration?

**Comment by git-e-up** [comment]
I did try adding the api_key to the migration to no avail. Also, I tried everything I could think of in the controller, but didn't do anything in the model. I will try that when I get home. If nothing works hopefully we will have time tomorrow?
Thanks!

**Comment by amadden80** [comment]
Here's what I did:

``` ruby
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :username
      t.string :password_digest
      t.string :api_key

      t.timestamps null: false
    end
  end
end
```

`rake db:drop`
`rake db:create`
`rake db:migrate`

That error goes away

**Comment by git-e-up** [comment]
Awesome! Thanks. Can't wait to check it out. I didn't realize you needed to drop the database and recreate it.
